service: lui_kit
image: k0va1/lui_kit

ssh:
  user: www

registry:
  server: ghcr.io
  username: k0va1
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  args:
    RUBY_VERSION: "3.3.5"
    NODE_VERSION: "20.18.1"
    RAILS_ENV: "production"

servers:
  web:
    hosts:
      - "49.13.117.76"
    options:
      memory: 512M

env:
  clear:
    RAILS_LOG_TO_STDOUT: 1
    RAILS_SERVE_STATIC_FILES: 1
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY

proxy:
  ssl: false
  app_port: 8000
  host: ui.lightningrails.xyz
  forward_headers: true
  healthcheck:
    interval: 3
    path: /up
    timeout: 3
  logging:
    request_headers:
      - Cache-Control
      - X-Forwarded-Proto
    response_headers:
      - X-Request-ID
      - X-Request-Start

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
