source "https://rubygems.org"

ruby "4.0.6"

gem "rails", "~> 8.0"
gem "puma", "~> 6.0"
gem "sqlite3"
gem "turbo-rails"
gem "stimulus-rails"
gem "lookbook", "~> 2.3"
gem "propshaft"

gem "lightning_ui_kit", path: "../"

group :development, :test do
  gem "foreman"
end

group :development do
  gem "listen"
  gem "web-console", ">= 4.1.0"
end
