source "https://rubygems.org"

ruby "3.3.5"

gem "rails", "~> 8.0"
gem "puma", "~> 6.0"
gem "sqlite3"
gem "turbo-rails"
gem "stimulus-rails"
gem "lookbook", "~> 2.3"
gem "propshaft"

if ENV["RAILS_ENV"] == "production"
  gem "lightning_ui_kit", git: "https://github.com/k0va1/lightning_ui_kit.git"
else
  gem "lightning_ui_kit", path: "../"
end

group :development, :test do
  gem "foreman"
end

group :development do
  gem "listen"
  gem "web-console", ">= 4.1.0"
end
